- name: Install a Monitoring Stack
  hosts: all
  become: yes
  vars:
    pip_install_packages:
      - name: docker

  roles:
    # - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Delete monitoring path
      command: rm -rf /srv/monitoring

    - name: Create a monitoring path
      command: mkdir /srv/monitoring

    - name: Git clone
      ansible.builtin.git:
        repo: 'https://github.com/YR72dpi/debianMonitoring.git'
        dest: /srv/monitoring

    - name: Install Docker-py
      command: pip install docker

    - name: Install Docker-Compose-py
      command: pip install docker-compose

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: /srv/monitoring
        state: absent

    - name: Create and start services
      community.docker.docker_compose:
        project_src: /srv/monitoring
        state: present
      register: output
    
    - name: Show results
      ansible.builtin.debug:
        var: output

    - name: Information Grafana
      ansible.builtin.debug:
        msg: "Go to [YOUR IP]:9200"