global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['51.178.24.72:9100']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets:  ['51.178.24.72:8090']